feat:Playlist관련 Entity, Repository 구현#16
Dev-Pepes/movie pull request #33
Opened 2023-09-17 11:05 UTC by wooki37

## 📝 PR Summary

Playlist 관련 Entity, Repository 작성

#### 🌲 Working Branch

feat/16-playlist-entity

#### 🌲 TODOs

PlaylistVideo Entity에 TODO: created_user 컬럼 나중에 추가해주기

### Related Issues

https://github.com/Dev-Pepes/playlist_be/issues/16

2023-09-17 15:09 UTC, bongsh0112 requested changes
고생하셨습니다 수정사항 반영하시고 다시 PR 올려주세용

2023-09-17 15:09 UTC, bongsh0112 commented on Domain/src/main/java/playlist/server/domain/domains/board/domain/Article.java
> +import jakarta.validation.constraints.NotNull;
NotNull 패키지 제대로 알기 좋습니다

2023-09-17 15:09 UTC, bongsh0112 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/Playlist.java
> +
`viewCount` 라고 명명하는것이 나아보이네요
또한 `조회수` 이므로 타입도`int`로 바꾸는게 맞는 것 같습니다.

2023-09-17 15:09 UTC, bongsh0112 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/Playlist.java
> +    private List<PlaylistLike> likes = new ArrayList<>();
`mappedBy` 와 `orphanRemoval` 좋습니다.
`Article` 엔티티와 비슷한 경우인 것 같은데
혹시 `fetch`와 `cascade`를 빼고 만든 이유가 있을까요?

2023-09-17 15:09 UTC, bongsh0112 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/Playlist.java
> +
TODO를 추가해주세요
> playlist 안에 들어갈 대표 동영상 5개정도의 객체를 집어넣을 예정입니다.
> 이것에 대한 TODO를 작성해주세요
> 또, `Tag` Entity의 List도 들어갈 예정이니 이것도 추가해주세요

2023-09-17 15:09 UTC, bongsh0112 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistLike.java
> +    private Playlist playlist;
`@JoinColumn` 어노테이션에서 왜 playlistId라고 이름을 지으신걸까요?

2023-09-17 15:09 UTC, bongsh0112 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistTaglist.java
> +}
어떤 Entity 안에 들어갈 다른 Entity의 List는 따로 클래스로 만들지 않아요
`PlaylistTag`라는 Entity를 만들어 `Playlist` Entity에 `List<PlaylistTag>`와 같이 넣는게 맞습니당

2023-09-17 15:09 UTC, bongsh0112 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistVideo.java
> +    private String countView;
이건 동영상 하나하나의 조회수를 말하는건가요?

2023-09-17 15:09 UTC, bongsh0112 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistVideo.java
> +public class PlaylistVideo extends AbstractTimeStamp {
굿굿 이렇게 Tag도 한번 만들어보세요

2023-09-17 15:09 UTC, bongsh0112 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistVideo.java
> +    private String totalVideos;
이건 뭘 뜻하는 필드인가요

2023-09-17 15:09 UTC, bongsh0112 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistVideo.java
> +    @NotNull private String videoPlaybackTime;
이건 동영상의 총 재생길이?

2023-09-18 01:50 UTC, wooki37 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistVideo.java
> +    @NotNull private String videoPlaybackTime;
totalVideos는 총 비디오 수 입니다!

2023-09-18 02:30 UTC, donsonioc2010 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistVideo.java
> +    @NotNull private String videoPlaybackTime;
갯수면 `int` 타입 또는 `long`타입이 더 적당하지 않을까요?

2023-09-18 13:36 UTC, wooki37 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistVideo.java
> +    private String totalVideos;
조회수이며, private String viewCount 로 수정하겠습니다.

2023-09-18 13:37 UTC, wooki37 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistVideo.java
> +    private String countView;
네! 각 동영상의 조회수이며, private String viewCount 로 수정하겠습니다

2023-09-18 13:40 UTC, wooki37 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistTaglist.java
> +}
리뷰감사합니다! 일대 다로 Playlist에 List<PlaylistTag>를 담도록 수정하겠습니다.

2023-09-18 13:47 UTC, wooki37 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistLike.java
> +    private Playlist playlist;
PlaylistLike가 articleId로 받은 좋아요가 넘겨져 와서 증가하는건지 헷갈립니다. 그래서 우선 playliskLike로 새 엔티티를 생성했고, playlistId로 받아오도록 하였습니다. 수정사항이 있으시면 말씀 부탁드립니다.

2023-09-18 13:51 UTC, wooki37 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/Playlist.java
> +
넵! 확인하였습니다~

2023-09-18 13:57 UTC, wooki37 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/Playlist.java
> +    private List<PlaylistLike> likes = new ArrayList<>();
추가하겠습니다~^^

2023-09-18 13:57 UTC, wooki37 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/Playlist.java
> +
네~!

2023-09-18 14:02 UTC, wooki37 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistVideo.java
> +    @NotNull private String videoPlaybackTime;
네 int 로 수정하겠습니다~

2023-09-18 15:41 UTC, bongsh0112 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistVideo.java
> +    @NotNull private String videoPlaybackTime;
플레이리스트 안의 총 비디오의 수 같은 경우는 `Video` 객체가 아니라
`Video`들을 가지고 있는 `Playlist`에 들어가는게 낫겠네요.
음 그리고 이런 갯수 같은 경우는 그냥 query 로 가져오는게 나을 수 있으니 우선 지워놓겠습니다!

2023-09-18 15:41 UTC, bongsh0112 commented on Domain/src/main/java/playlist/server/domain/domains/playlist/repository/PlaylistTaglistRepository.java
> +public interface PlaylistTaglistRepository extends JpaRepository<PlaylistTag, Long> {}
왜 `PlaylistTaglist` 레포지토리죠?

2023-09-21 05:21 UTC, bongsh0112 approved these changes

2023-09-21 05:21 UTC, merged